### ISSUE TITLE
Review #1: Potential improvements/fixes

### ISSUE THREAD

**Issue by oakw** [mihaildanilov/TheRaccoons#11]
1. Seems that there was more free space previously around elements. Not necessary to have as much as previously, but it feels a bit squashed now.

![Capture d’écran (841)](https://github.com/mihaildanilov/TheRaccoons/assets/80841359/6d8f0694-5ce7-40e9-bc68-7e53c7e832b0)

2. _Friends_ on the home page fall off the boundaries of padded content pretty much.
3. Page locks (scroll bar disappears) when language selection is active.
4. Seems that Hackathon 2023 and the home page have different font sizes. It just feels different.
5. Buttons on the home page are not centered on home screens.

**Comment by mihaildanilov** [comment]
## Update on Task 3

The issue with the page locking (scroll bar disappearing) when the language selection is active has been addressed and implemented successfully. Users should no longer experience this problem.

**Comment by mihaildanilov** [comment]
## Update: All Tasks Completed

All tasks related to the reported UI issues on the home page have been successfully implemented and tested. The changes include adjustments to spacing, padding, and font sizes, along with resolving issues like the disappearing scroll bar during language selection and misalignment of buttons. 

Please feel free to review the changes, and if you have any additional feedback or concerns, don't hesitate to let me know. Your input is valuable, and I appreciate your collaboration.
